### ISSUE TITLE
Better Discord Themes dont work!?

### ISSUE THREAD

**Issue by YukinoKirigaya** [awaken1ng/bd-linestickers#16]
I downloaded the clear theme and better discord but only the top bar where it says discord has the theme, all the rest is normal discord!?
![image](https://user-images.githubusercontent.com/35821703/35418717-07e7edf8-0202-11e8-8d4e-866f31cc3998.png)

**Comment by awaken1ng** [comment]
Not plugin related, but here's CSS snippet from BD support servers, add it to your custom CSS, adjust if needed
```css
/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}
/* optionally adjust background brightness (0: original image, 1: black) */
.layers-20RVFW {
  background: rgba(0,0,0, 0.3) !important;
}
```
Alternatively, wait for an update, [here's](https://github.com/Dddsasul/TeamKappa-theme) what looks like the theme repo
